version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: animales_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: animales
      POSTGRES_HOST_AUTH_METHOD: trust 
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
